### PR TITLE
Console configuration additions, and renaming director service for RHEL systems

### PR DESCRIPTION
**Pull request by mttjdvs**

### CODE REVIEW

**Comment by lightoze** [comment]
On CentOS 7 it is `bacula-director`.

**Comment by mttjdvs** [comment]
Ah. Was wondering if that would be the case. So some logic for version may be in order.

**Comment by lightoze** [comment]
As I understand, this change enables console client to access all daemons directly with monitor permissions. But there is already a configuration of administrator access to the director. How do you use this extra configuration?

**Comment by mttjdvs** [comment]
With the previous configuration, operations in bconsole would frequently cause the storage daemon to crash. This configuration seems to fix that, but I'm wondering now if it is specific to the package for my kernel. If so, this change is likely superfluous. In any case, I should need to do some re-tooling before a potential merge.

**Pull request closed without merging**
